### ISSUE TITLE
Event loop is closed

### ISSUE THREAD

**Issue by JINHYUKJEONG** [djkelleher/crawler-cluster#1]
![image](https://user-images.githubusercontent.com/17464885/122635502-4e226380-d11f-11eb-8322-f7f0da66e6fd.png)
There are a total of 9 elements and I have 2 loader counts. So, isn't it two, two, two, two, one, running at the same time like this? After finishing the first two tasks and closing all of the chrome windows, I thought that the two would run again and do other tasks, but an error occurs while trying to start a new task with the two windows of the previously opened task remaining.

**Comment by djkelleher** [comment]
Hi, why are you closing the chrome windows? The `QueueClient` class wraps your script and is designed to recover from errors in your script. This may be what you're looking for. The `MultiLoaderClient` can not do this as it is part of your script, rather than wrapping your script.
